Employee
Kura33/ProjectJavaCesi pull request #6
Opened 2021-03-15 13:42 UTC by Kura33

merge models employee.

2021-03-15 14:03 UTC, Zekemaz approved these changes

2021-03-15 17:58 UTC, Kura33 reviewed
ok

2021-03-15 21:05 UTC, mcpeyran requested changes

2021-03-15 21:05 UTC, mcpeyran commented on src/main/java/com/shield/projectJavaCesi/entity/employee/Employee.java
> +		CDI("CDI"), CDD("CDD"), ALTERNANCE("Alternance"), STAGE("Stage"), NOT_CONCERNED("N/C");
Dans Incident les clés des variables de énum sont en anglais, les valeurs en français. Ici les deux sont en français. On devrait choisir l'un ou l'autre, celui que tu veux. Merci : )

2021-03-16 07:16 UTC, Zekemaz approved these changes

2021-03-16 07:18 UTC, Zekemaz commented on src/main/java/com/shield/projectJavaCesi/entity/employee/Employee.java
> +		CDI("CDI"), CDD("CDD"), ALTERNANCE("Alternance"), STAGE("Stage"), NOT_CONCERNED("N/C");
Je suis d'accord, 

- CDI : OPEN_ENDED_CONTRACT
- CDD : FIXED_TERM_CONTRACT
- ALTERNANCE : APPRENTICESHIP
- STAGE : INTERNSHIP
- NOT_CONCERNED est bon :)

2021-03-16 07:19 UTC, Zekemaz requested changes
Je suis d'accord avec le commentaire de Marie-Cécile

CDI : OPEN_ENDED_CONTRACT
CDD : FIXED_TERM_CONTRACT
ALTERNANCE : APPRENTICESHIP
STAGE : INTERNSHIP
NOT_CONCERNED est bon :)

2021-03-16 07:39 UTC, mcpeyran approved these changes

2021-03-16 07:43 UTC, Zekemaz approved these changes

2021-03-16 09:29 UTC, merged